name: Mario E Reyes
favicon: null
layout_spectrum: 0.048913451144471765
typography_spectrum: 0.6634885335806757
title: Espacio Inteligente
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8323863642290235
  lightness: 0.30496379639953375
  saturation: 0.8056057244539261
  rhythmicContrast: 0.8691500874701887
purpose: []
